version: '3'
services:
  web:
    image: node:latest
    container_name: boilerplate
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "yarn global add gulp && yarn install && yarn start"
